"""
Physical plausibility assessment utilities.

Overview
--------
This module provides post-processing utilities for assessing whether candidate
materials are physically plausible based on inexpensive structural and
chemical evidence already generated by the Phase 1 pipeline.

Design goals
------------
* Preserve the evidence-driven architecture.
* Avoid modifying retrieval, ranking or role assignment logic.
* Provide transparent annotations explaining why a candidate appears
  physically plausible or warrants caution.
* Remain computationally inexpensive so it can be applied to large batches.

Developer notes
---------------
This module forms part of the "cheap context first" workflow. It should not
introduce expensive calculations or external simulations. New plausibility
checks should be deterministic, documented, and justified so that future
contributors can understand both their intent and limitations.

"""
from __future__ import annotations

"""
physical_plausibility.py

Physical plausibility annotation utilities for the Cheap Context First framework.

Purpose
-------
Adds conservative physical plausibility metadata to retrieval results without
changing similarity scores, rankings or role assignments. The module is intended
to improve interpretability rather than predictive performance.

Responsibilities
----------------
* Annotate individual materials using formation energy, energy above hull and
  synthesis evidence where available.
* Produce pair-level plausibility assessments for retrieved neighbours.
* Preserve deterministic behaviour and avoid altering retrieval outputs.
* Gracefully handle missing physical data.

Dependencies
------------
External:
* pandas (optional, for dataframe annotation)

Internal:
* Material store object exposing material metadata.

Public entry points
-------------------
* PhysicalPlausibilityAnnotator
* PhysicalPlausibilityConfig

Maintenance notes
-----------------
This module is designed to be largely self-contained. Thresholds should only be
changed after validation because downstream reports assume stable semantics.
"""

from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from enum import Enum
import json
import logging
import math
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple

try:
    import pandas as pd
except Exception:  # pragma: no cover - allows import in non-pandas contexts
    pd = None  # type: ignore


PHYSICAL_PLAUSIBILITY_SCHEMA_VERSION = "phase3.physical_plausibility.v1"
PHYSICAL_PLAUSIBILITY_OUTPUT_COLUMNS: Tuple[str, ...] = (
    "formation_energy_a",
    "formation_energy_b",
    "energy_above_hull_a",
    "energy_above_hull_b",
    "known_synthesized_a",
    "known_synthesized_b",
    "physical_plausibility_label_a",
    "physical_plausibility_label_b",
    "physical_plausibility_score_a",
    "physical_plausibility_score_b",
    "physical_plausibility_flags_a",
    "physical_plausibility_flags_b",
    "pair_physical_plausibility_label",
    "pair_physical_plausibility_score",
    "physical_data_completeness",
    "physical_plausibility_flags",
    "physical_plausibility_evidence",
    "physical_plausibility_summary",
    "physical_plausibility_schema_version",
)
LOGGER_NAME = "lrt.physical_plausibility"
logger = logging.getLogger(LOGGER_NAME)


# =============================================================================
# Labels / configuration
# =============================================================================


class MaterialPhysicalLabel(str, Enum):
    """Stable string labels for material-level physical plausibility."""

    STABLE_OR_KNOWN = "stable_or_known"
    METASTABLE_OR_UNCERTAIN = "metastable_or_uncertain"
    HIGH_METASTABILITY_WARNING = "high_metastability_warning"
    PHYSICALLY_DUBIOUS = "physically_dubious"
    INSUFFICIENT_DATA = "insufficient_data"


class PairPhysicalLabel(str, Enum):
    """Stable string labels for pair-level physical plausibility."""

    PLAUSIBLE_PAIR = "plausible_pair"
    PLAUSIBLE_BUT_UNCERTAIN = "plausible_but_uncertain"
    TOPOLOGY_ONLY_WARNING = "topology_only_warning"
    PHYSICALLY_DUBIOUS_PAIR = "physically_dubious_pair"
    INSUFFICIENT_DATA = "insufficient_data"


@dataclass(frozen=True)
class PhysicalPlausibilityConfig:
    """
    Configuration for Phase 2 physical plausibility annotation.

    Thresholds are in eV/atom where the source data is eV/atom. The defaults are
    intentionally soft and should be treated as annotation rules, not scientific
    proof of synthesizability.
    """

    ehull_stable_threshold: float = 0.025
    ehull_metastable_threshold: float = 0.100
    ehull_high_metastability_threshold: float = 0.200
    formation_energy_positive_dubious: bool = True
    positive_formation_energy_flag_threshold: float = 0.0
    known_synthesized_bonus: float = 0.25
    missing_data_penalty: float = 0.15
    soft_filter_enabled: bool = False
    pair_dubious_score_threshold: float = 0.40

    formation_energy_aliases: Tuple[str, ...] = (
        "formation_energy",
        "formation_energy_peratom",
        "form_energy_peratom",
        "formation_energy_per_atom",
        "formation_energy_pa",
    )
    energy_above_hull_aliases: Tuple[str, ...] = (
        "energy_above_hull",
        "ehull",
        "e_above_hull",
        "e_above_hull_per_atom",
        "energy_above_hull_peratom",
    )
    known_synthesized_aliases: Tuple[str, ...] = (
        "known_synthesized",
        "is_synthesized",
        "synthesized",
        "experimentally_synthesized",
        "icsd",
        "icsd_id",
    )
    schema_version: str = PHYSICAL_PLAUSIBILITY_SCHEMA_VERSION

    def to_dict(self) -> Dict[str, Any]:
        payload = asdict(self)
        for key, value in list(payload.items()):
            if isinstance(value, tuple):
                payload[key] = list(value)
        return payload

    @classmethod
    def from_mapping(cls, payload: Mapping[str, Any]) -> "PhysicalPlausibilityConfig":
        data = dict(payload or {})
        for key in ("formation_energy_aliases", "energy_above_hull_aliases", "known_synthesized_aliases"):
            if key in data and not isinstance(data[key], tuple):
                data[key] = tuple(data[key])
        return cls(**data)

    @classmethod
    def from_json(cls, path: str | Path) -> "PhysicalPlausibilityConfig":
        with open(path, "r", encoding="utf-8") as f:
            return cls.from_mapping(json.load(f))

    def write_json(self, path: str | Path) -> None:
        out = Path(path)
        out.parent.mkdir(parents=True, exist_ok=True)
        with open(out, "w", encoding="utf-8") as f:
            json.dump(self.to_dict(), f, indent=2, sort_keys=True)


@dataclass(frozen=True)
class MaterialPhysicalAnnotation:
    jid: Optional[str]
    formation_energy: Optional[float]
    energy_above_hull: Optional[float]
    known_synthesized: Optional[bool]
    label: str
    score: float
    flags: Tuple[str, ...]
    evidence: Tuple[str, ...]
    data_completeness: float


@dataclass(frozen=True)
class PairPhysicalAnnotation:
    jid_a: Optional[str]
    jid_b: Optional[str]
    label: str
    score: float
    flags: Tuple[str, ...]
    evidence: Tuple[str, ...]
    data_completeness: float
    material_a: MaterialPhysicalAnnotation
    material_b: MaterialPhysicalAnnotation


# =============================================================================
# Generic helpers
# =============================================================================



# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def safe_float(value: Any) -> Optional[float]:
    """Convert a value to a finite float, returning None on missing/bad values."""

    try:
        if value is None:
            return None
        if isinstance(value, str):
            stripped = value.strip()
            if stripped == "" or stripped.lower() in {"nan", "none", "null", "na", "n/a"}:
                return None
            value = stripped
        number = float(value)
        if math.isnan(number) or math.isinf(number):
            return None
        return number
    except Exception:
        return None


def safe_bool(value: Any) -> Optional[bool]:
    """Parse common boolean/synthesis-status values."""

    if value is None:
        return None
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        if math.isnan(value) if isinstance(value, float) else False:
            return None
        return bool(value)
    if isinstance(value, str):
        stripped = value.strip().lower()
        if stripped in {"", "none", "null", "nan", "na", "n/a", "unknown"}:
            return None
        if stripped in {"true", "t", "yes", "y", "1", "synthesized", "known", "experimental", "experiment"}:
            return True
        if stripped in {"false", "f", "no", "n", "0", "not_synthesized", "not synthesized"}:
            return False
        # ICSD-like identifiers are often non-empty strings. Treat as evidence.
        return True
    return None


def first_present(mapping: Mapping[str, Any], aliases: Sequence[str]) -> Any:
    """Return the first non-empty value from a mapping using possible aliases."""

    for key in aliases:
        if key in mapping:
            value = mapping.get(key)
            if value is not None:
                if isinstance(value, str) and not value.strip():
                    continue
                return value
    return None


def _as_serialized_flags(flags: Iterable[str]) -> str:
    """Stable semicolon-delimited representation for CSV outputs."""

    unique = []
    seen = set()
    for flag in flags:
        if flag and flag not in seen:
            unique.append(flag)
            seen.add(flag)
    return ";".join(unique)


def _material_severity(label: str) -> int:
    """Higher is worse. Used for pair aggregation."""

    order = {
        MaterialPhysicalLabel.STABLE_OR_KNOWN.value: 0,
        MaterialPhysicalLabel.METASTABLE_OR_UNCERTAIN.value: 1,
        MaterialPhysicalLabel.HIGH_METASTABILITY_WARNING.value: 2,
        MaterialPhysicalLabel.PHYSICALLY_DUBIOUS.value: 3,
        MaterialPhysicalLabel.INSUFFICIENT_DATA.value: 2,
    }
    return order.get(str(label), 2)


# =============================================================================
# Core annotator
# =============================================================================




def configure_physical_plausibility_logging(level: int = logging.INFO, log_file: Optional[str | Path] = None) -> logging.Logger:
    """Configure module logging in a reusable, idempotent way."""

    logger.setLevel(level)
    if not any(isinstance(h, logging.StreamHandler) and getattr(h, "_lrt_console", False) for h in logger.handlers):
        handler = logging.StreamHandler()
        handler._lrt_console = True  # type: ignore[attr-defined]
        handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)s %(name)s - %(message)s"))
        logger.addHandler(handler)
    if log_file is not None:
        log_path = Path(log_file)
        log_path.parent.mkdir(parents=True, exist_ok=True)
        file_handler = logging.FileHandler(log_path, encoding="utf-8")
        file_handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)s %(name)s - %(message)s"))
        logger.addHandler(file_handler)
    return logger


def validate_physical_plausibility_config(config: PhysicalPlausibilityConfig) -> None:
    """Fail fast on ambiguous physical-plausibility thresholds."""

    if not (0 <= config.ehull_stable_threshold <= config.ehull_metastable_threshold <= config.ehull_high_metastability_threshold):
        raise ValueError("ehull thresholds must be ordered: stable <= metastable <= high_metastability.")
    if not (0 <= config.known_synthesized_bonus <= 1):
        raise ValueError("known_synthesized_bonus must be between 0 and 1.")
    if not (0 <= config.missing_data_penalty <= 1):
        raise ValueError("missing_data_penalty must be between 0 and 1.")
    if not (0 <= config.pair_dubious_score_threshold <= 1):
        raise ValueError("pair_dubious_score_threshold must be between 0 and 1.")


def physical_plausibility_manifest(config: PhysicalPlausibilityConfig) -> Dict[str, Any]:
    """Return stable metadata for downstream run manifests."""

    return {
        "schema_version": PHYSICAL_PLAUSIBILITY_SCHEMA_VERSION,
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "config": config.to_dict(),
        "material_labels": [label.value for label in MaterialPhysicalLabel],
        "pair_labels": [label.value for label in PairPhysicalLabel],
        "output_columns": list(PHYSICAL_PLAUSIBILITY_OUTPUT_COLUMNS),
    }


def validate_physical_output_schema(df: Any, require_all_columns: bool = True) -> None:
    """Validate expected physical-plausibility output columns."""

    if pd is None:
        raise RuntimeError("pandas is required for validate_physical_output_schema().")
    missing = [col for col in PHYSICAL_PLAUSIBILITY_OUTPUT_COLUMNS if col not in df.columns]
    if require_all_columns and missing:
        raise ValueError(f"Physical plausibility output is missing required columns: {missing}")


class PhysicalPlausibilityAnnotator:
    """
    Adds physical plausibility metadata to material and pair records.

    Parameters
    ----------
    material_lookup:
        Mapping from JID to material records. Records may be dictionaries,
        MaterialRecord-like objects with `.raw` / `.features`, pandas rows, or
        mixed objects. The annotator extracts fields defensively.
    config:
        Thresholds and aliases.
    known_synthesized_map:
        Optional external mapping from JID to known synthesized status. This is
        useful because known synthesized status is often absent from JARVIS raw
        fields.
    """

    def __init__(
        self,
        material_lookup: Optional[Mapping[str, Any]] = None,
        config: Optional[PhysicalPlausibilityConfig] = None,
        known_synthesized_map: Optional[Mapping[str, Any]] = None,
    ) -> None:
        self.material_lookup: Dict[str, Any] = dict(material_lookup or {})
        self.config = config or PhysicalPlausibilityConfig()
        validate_physical_plausibility_config(self.config)
        self.known_synthesized_map: Dict[str, Optional[bool]] = {
            str(k): safe_bool(v) for k, v in dict(known_synthesized_map or {}).items()
        }
        self._annotation_cache: Dict[Optional[str], MaterialPhysicalAnnotation] = {}

    @classmethod
    def from_material_store(
        cls,
        store: Any,
        config: Optional[PhysicalPlausibilityConfig] = None,
        known_synthesized_map: Optional[Mapping[str, Any]] = None,
    ) -> "PhysicalPlausibilityAnnotator":
        """
        Construct an annotator from a MaterialStore-like object.

        The method intentionally uses duck typing to avoid coupling this module
        tightly to one material_store.py implementation.
        """

        lookup: Dict[str, Any] = {}

        if hasattr(store, "ensure_universe"):
            try:
                store.ensure_universe()
            except Exception as exc:
                logger.warning("Could not eagerly build material-store universe for plausibility lookup: %s", exc)

        # Common case: a store exposes a dataframe-like `universe_df` or `df`.
        for attr in ("universe_df", "materials_df", "df", "material_df"):
            obj = getattr(store, attr, None)
            if pd is not None and obj is not None and hasattr(obj, "iterrows") and "jid" in obj.columns:
                for _, row in obj.iterrows():
                    jid = row.get("jid")
                    if jid is not None:
                        lookup[str(jid)] = row.to_dict()
                break

        # Fallback: known dict-like lookup fields.
        for attr in ("records", "material_records", "record_by_jid", "materials_by_jid", "lookup"):
            obj = getattr(store, attr, None)
            if isinstance(obj, Mapping):
                for jid, record in obj.items():
                    lookup[str(jid)] = record

        # Last resort: if the store exposes resolve(), keep a thin proxy rather
        # than enumerating everything. annotate_material handles callable lookup.
        if not lookup and hasattr(store, "resolve"):
            lookup["__STORE_PROXY__"] = store

        return cls(lookup, config=config, known_synthesized_map=known_synthesized_map)

    @classmethod
    def from_dataframe(
        cls,
        material_df: Any,
        config: Optional[PhysicalPlausibilityConfig] = None,
        known_synthesized_map: Optional[Mapping[str, Any]] = None,
    ) -> "PhysicalPlausibilityAnnotator":
        """Construct from a dataframe with a jid column."""

        if pd is None:
            raise RuntimeError("pandas is required for from_dataframe().")
        if "jid" not in material_df.columns:
            raise ValueError("material_df must contain a 'jid' column.")
        lookup = {str(row["jid"]): row.to_dict() for _, row in material_df.iterrows()}
        return cls(lookup, config=config, known_synthesized_map=known_synthesized_map)

    @classmethod
    def from_known_synthesized_csv(
        cls,
        material_lookup: Optional[Mapping[str, Any]],
        csv_path: str | Path,
        config: Optional[PhysicalPlausibilityConfig] = None,
        jid_column: str = "jid",
        status_column: str = "known_synthesized",
    ) -> "PhysicalPlausibilityAnnotator":
        """Construct with an external known-synthesized CSV map."""

        if pd is None:
            raise RuntimeError("pandas is required for from_known_synthesized_csv().")
        df = pd.read_csv(csv_path)
        if jid_column not in df.columns or status_column not in df.columns:
            raise ValueError(f"CSV must contain columns '{jid_column}' and '{status_column}'.")
        mapping = {str(row[jid_column]): row[status_column] for _, row in df.iterrows()}
        return cls(material_lookup=material_lookup, config=config, known_synthesized_map=mapping)

    # ------------------------------------------------------------------
    # Material annotation
    # ------------------------------------------------------------------

    def annotate_material(self, jid: Optional[str], material: Optional[Any] = None) -> MaterialPhysicalAnnotation:
        """Return physical plausibility annotation for one material."""

        jid_key = str(jid) if jid is not None else None
        if material is None and jid_key in self._annotation_cache:
            return self._annotation_cache[jid_key]

        record = material if material is not None else self._get_material_record(jid_key)
        flattened = self._flatten_material_record(record)

        formation_energy = safe_float(first_present(flattened, self.config.formation_energy_aliases))
        energy_above_hull = safe_float(first_present(flattened, self.config.energy_above_hull_aliases))

        known_synthesized = None
        if jid_key in self.known_synthesized_map:
            known_synthesized = self.known_synthesized_map.get(jid_key)
        if known_synthesized is None:
            known_synthesized = safe_bool(first_present(flattened, self.config.known_synthesized_aliases))

        annotation = self._classify_material(
            jid=jid_key,
            formation_energy=formation_energy,
            energy_above_hull=energy_above_hull,
            known_synthesized=known_synthesized,
        )
        if material is None:
            self._annotation_cache[jid_key] = annotation
        return annotation

    def _classify_material(
        self,
        jid: Optional[str],
        formation_energy: Optional[float],
        energy_above_hull: Optional[float],
        known_synthesized: Optional[bool],
    ) -> MaterialPhysicalAnnotation:
        flags: List[str] = []
        evidence: List[str] = []
        available = 0
        possible = 3

        if formation_energy is not None:
            available += 1
            evidence.append(f"formation_energy={formation_energy:.6g}")
            if self.config.formation_energy_positive_dubious and formation_energy > self.config.positive_formation_energy_flag_threshold:
                flags.append("positive_formation_energy")
        else:
            flags.append("missing_formation_energy")

        if energy_above_hull is not None:
            available += 1
            evidence.append(f"energy_above_hull={energy_above_hull:.6g}")
        else:
            flags.append("missing_energy_above_hull")

        if known_synthesized is not None:
            available += 1
            evidence.append(f"known_synthesized={known_synthesized}")
        else:
            flags.append("missing_known_synthesized_status")

        data_completeness = available / possible

        if known_synthesized is True and energy_above_hull is None:
            label = MaterialPhysicalLabel.STABLE_OR_KNOWN.value
            score = 0.85
            flags.append("known_synthesized_no_ehull")
        elif energy_above_hull is None:
            label = MaterialPhysicalLabel.INSUFFICIENT_DATA.value
            score = 0.50 - self.config.missing_data_penalty
        elif energy_above_hull <= self.config.ehull_stable_threshold:
            label = MaterialPhysicalLabel.STABLE_OR_KNOWN.value
            score = 0.95
        elif energy_above_hull <= self.config.ehull_metastable_threshold:
            label = MaterialPhysicalLabel.METASTABLE_OR_UNCERTAIN.value
            score = 0.75
            flags.append("metastable_energy_above_hull")
        elif energy_above_hull <= self.config.ehull_high_metastability_threshold:
            label = MaterialPhysicalLabel.HIGH_METASTABILITY_WARNING.value
            score = 0.55
            flags.append("high_metastability_energy_above_hull")
        else:
            label = MaterialPhysicalLabel.PHYSICALLY_DUBIOUS.value
            score = 0.25
            flags.append("high_energy_above_hull")

        if known_synthesized is True:
            score = min(1.0, score + self.config.known_synthesized_bonus)
            flags.append("known_synthesized_support")
            if label == MaterialPhysicalLabel.PHYSICALLY_DUBIOUS.value:
                # Keep the warning but avoid implying the material is impossible.
                label = MaterialPhysicalLabel.HIGH_METASTABILITY_WARNING.value
                flags.append("known_synthesized_overrides_dubious_label_to_warning")

        if known_synthesized is False:
            flags.append("no_known_synthesis_support")

        if formation_energy is not None and formation_energy > self.config.positive_formation_energy_flag_threshold:
            score = min(score, 0.60)
            if label == MaterialPhysicalLabel.STABLE_OR_KNOWN.value and known_synthesized is not True:
                label = MaterialPhysicalLabel.METASTABLE_OR_UNCERTAIN.value

        score = max(0.0, min(1.0, score))
        return MaterialPhysicalAnnotation(
            jid=jid,
            formation_energy=formation_energy,
            energy_above_hull=energy_above_hull,
            known_synthesized=known_synthesized,
            label=label,
            score=score,
            flags=tuple(dict.fromkeys(flags)),
            evidence=tuple(evidence),
            data_completeness=data_completeness,
        )

    # ------------------------------------------------------------------
    # Pair annotation
    # ------------------------------------------------------------------

    def annotate_pair(
        self,
        jid_a: Optional[str],
        jid_b: Optional[str],
        material_a: Optional[Any] = None,
        material_b: Optional[Any] = None,
    ) -> PairPhysicalAnnotation:
        """Return pair-level physical plausibility annotation."""

        ann_a = self.annotate_material(jid_a, material=material_a)
        ann_b = self.annotate_material(jid_b, material=material_b)
        label = self._combine_pair_label(ann_a, ann_b)
        score = min(ann_a.score, ann_b.score)
        completeness = (ann_a.data_completeness + ann_b.data_completeness) / 2.0

        flags: List[str] = []
        flags.extend(f"a:{flag}" for flag in ann_a.flags)
        flags.extend(f"b:{flag}" for flag in ann_b.flags)

        if label == PairPhysicalLabel.TOPOLOGY_ONLY_WARNING.value:
            flags.append("structurally_interesting_but_physical_warning")
        elif label == PairPhysicalLabel.PHYSICALLY_DUBIOUS_PAIR.value:
            flags.append("pair_physically_dubious")
        elif label == PairPhysicalLabel.INSUFFICIENT_DATA.value:
            flags.append("pair_insufficient_physical_data")

        evidence = [
            f"a_label={ann_a.label}",
            f"b_label={ann_b.label}",
            *[f"a:{item}" for item in ann_a.evidence],
            *[f"b:{item}" for item in ann_b.evidence],
        ]

        return PairPhysicalAnnotation(
            jid_a=str(jid_a) if jid_a is not None else None,
            jid_b=str(jid_b) if jid_b is not None else None,
            label=label,
            score=max(0.0, min(1.0, score)),
            flags=tuple(dict.fromkeys(flags)),
            evidence=tuple(evidence),
            data_completeness=max(0.0, min(1.0, completeness)),
            material_a=ann_a,
            material_b=ann_b,
        )

    def _combine_pair_label(
        self,
        ann_a: MaterialPhysicalAnnotation,
        ann_b: MaterialPhysicalAnnotation,
    ) -> str:
        labels = {ann_a.label, ann_b.label}
        severities = [_material_severity(ann_a.label), _material_severity(ann_b.label)]

        if MaterialPhysicalLabel.PHYSICALLY_DUBIOUS.value in labels:
            if labels == {MaterialPhysicalLabel.PHYSICALLY_DUBIOUS.value}:
                return PairPhysicalLabel.PHYSICALLY_DUBIOUS_PAIR.value
            return PairPhysicalLabel.TOPOLOGY_ONLY_WARNING.value

        if MaterialPhysicalLabel.INSUFFICIENT_DATA.value in labels:
            if max(severities) >= 3:
                return PairPhysicalLabel.TOPOLOGY_ONLY_WARNING.value
            return PairPhysicalLabel.INSUFFICIENT_DATA.value

        if MaterialPhysicalLabel.HIGH_METASTABILITY_WARNING.value in labels:
            return PairPhysicalLabel.TOPOLOGY_ONLY_WARNING.value

        if MaterialPhysicalLabel.METASTABLE_OR_UNCERTAIN.value in labels:
            return PairPhysicalLabel.PLAUSIBLE_BUT_UNCERTAIN.value

        return PairPhysicalLabel.PLAUSIBLE_PAIR.value

    # ------------------------------------------------------------------
    # Dataframe annotation
    # ------------------------------------------------------------------

    def annotate_pair_dataframe(
        self,
        pair_df: Any,
        jid_a_col: Optional[str] = None,
        jid_b_col: Optional[str] = None,
        preserve_rank_columns: bool = True,
    ) -> Any:
        """
        Add physical plausibility columns to a pair/retrieval dataframe.

        The method preserves all existing columns and row order. It does not sort,
        filter, or alter retrieval ranking columns.
        """

        if pd is None:
            raise RuntimeError("pandas is required for annotate_pair_dataframe().")
        if pair_df is None:
            raise ValueError("pair_df cannot be None.")

        df = pair_df.copy()
        original_order = list(df.index)
        original_rank_values = {}
        if preserve_rank_columns:
            for col in ("retrieval_rank", "rank", "framework_rank"):
                if col in df.columns:
                    original_rank_values[col] = df[col].copy()

        resolved_a_col, resolved_b_col = self._resolve_pair_jid_columns(df, jid_a_col, jid_b_col)
        annotations: List[PairPhysicalAnnotation] = []

        for _, row in df.iterrows():
            jid_a = row.get(resolved_a_col) if resolved_a_col else None
            jid_b = row.get(resolved_b_col) if resolved_b_col else None
            annotations.append(self.annotate_pair(jid_a, jid_b))

        df["formation_energy_a"] = [ann.material_a.formation_energy for ann in annotations]
        df["formation_energy_b"] = [ann.material_b.formation_energy for ann in annotations]
        df["energy_above_hull_a"] = [ann.material_a.energy_above_hull for ann in annotations]
        df["energy_above_hull_b"] = [ann.material_b.energy_above_hull for ann in annotations]
        df["known_synthesized_a"] = [ann.material_a.known_synthesized for ann in annotations]
        df["known_synthesized_b"] = [ann.material_b.known_synthesized for ann in annotations]
        df["physical_plausibility_label_a"] = [ann.material_a.label for ann in annotations]
        df["physical_plausibility_label_b"] = [ann.material_b.label for ann in annotations]
        df["physical_plausibility_score_a"] = [ann.material_a.score for ann in annotations]
        df["physical_plausibility_score_b"] = [ann.material_b.score for ann in annotations]
        df["physical_plausibility_flags_a"] = [_as_serialized_flags(ann.material_a.flags) for ann in annotations]
        df["physical_plausibility_flags_b"] = [_as_serialized_flags(ann.material_b.flags) for ann in annotations]
        df["pair_physical_plausibility_label"] = [ann.label for ann in annotations]
        df["pair_physical_plausibility_score"] = [ann.score for ann in annotations]
        df["physical_data_completeness"] = [ann.data_completeness for ann in annotations]
        df["physical_plausibility_flags"] = [_as_serialized_flags(ann.flags) for ann in annotations]
        df["physical_plausibility_evidence"] = [_as_serialized_flags(ann.evidence) for ann in annotations]
        df["physical_plausibility_summary"] = [self._pair_summary(ann) for ann in annotations]
        df["physical_plausibility_schema_version"] = PHYSICAL_PLAUSIBILITY_SCHEMA_VERSION
        validate_physical_output_schema(df, require_all_columns=True)

        # Defensive rank/order preservation checks. If these trip, integration code
        # has probably sorted elsewhere, because this method does not.
        if list(df.index) != original_order:
            raise RuntimeError("annotate_pair_dataframe changed dataframe row order unexpectedly.")
        for col, values in original_rank_values.items():
            if not df[col].equals(values):
                raise RuntimeError(f"annotate_pair_dataframe changed rank column '{col}' unexpectedly.")

        return df

    def soft_filter_pair_dataframe(
        self,
        annotated_pair_df: Any,
        allowed_labels: Optional[Sequence[str]] = None,
    ) -> Any:
        """
        Return a soft-filtered *view* of an already annotated dataframe.

        This is intentionally separate from annotate_pair_dataframe so Phase 2 can
        produce physically less-dubious views without changing core retrieval.
        """

        if pd is None:
            raise RuntimeError("pandas is required for soft_filter_pair_dataframe().")
        if "pair_physical_plausibility_label" not in annotated_pair_df.columns:
            raise ValueError("Input dataframe must first be annotated with annotate_pair_dataframe().")
        allowed = set(
            allowed_labels
            or [
                PairPhysicalLabel.PLAUSIBLE_PAIR.value,
                PairPhysicalLabel.PLAUSIBLE_BUT_UNCERTAIN.value,
                PairPhysicalLabel.INSUFFICIENT_DATA.value,
            ]
        )
        return annotated_pair_df[annotated_pair_df["pair_physical_plausibility_label"].isin(allowed)].copy()

    def summarize_pair_dataframe(self, annotated_pair_df: Any, top_k: int = 50) -> Dict[str, Any]:
        """Produce compact diagnostics for reports and summary JSON files."""

        if pd is None:
            raise RuntimeError("pandas is required for summarize_pair_dataframe().")
        if "pair_physical_plausibility_label" not in annotated_pair_df.columns:
            raise ValueError("Input dataframe must first be annotated with annotate_pair_dataframe().")

        df = annotated_pair_df.copy()
        top_df = df.head(top_k)
        label_counts = df["pair_physical_plausibility_label"].value_counts(dropna=False).to_dict()
        top_label_counts = top_df["pair_physical_plausibility_label"].value_counts(dropna=False).to_dict()

        def frac(label: str, frame: Any) -> float:
            if len(frame) == 0:
                return 0.0
            return float((frame["pair_physical_plausibility_label"] == label).mean())

        return {
            "schema_version": PHYSICAL_PLAUSIBILITY_SCHEMA_VERSION,
            "row_count": int(len(df)),
            "top_k": int(top_k),
            "physical_plausibility_label_counts": {str(k): int(v) for k, v in label_counts.items()},
            "top_k_physical_plausibility_label_counts": {str(k): int(v) for k, v in top_label_counts.items()},
            "top_k_physically_dubious_fraction": frac(PairPhysicalLabel.PHYSICALLY_DUBIOUS_PAIR.value, top_df),
            "top_k_topology_only_warning_fraction": frac(PairPhysicalLabel.TOPOLOGY_ONLY_WARNING.value, top_df),
            "top_k_insufficient_data_fraction": frac(PairPhysicalLabel.INSUFFICIENT_DATA.value, top_df),
            "mean_pair_physical_plausibility_score": float(df["pair_physical_plausibility_score"].mean()) if len(df) else 0.0,
            "mean_physical_data_completeness": float(df["physical_data_completeness"].mean()) if len(df) else 0.0,
        }

    def get_manifest(self) -> Dict[str, Any]:
        """Return physical-plausibility metadata suitable for run manifests."""

        return physical_plausibility_manifest(self.config)

    def write_manifest(self, path: str | Path) -> None:
        """Write physical-plausibility metadata to JSON."""

        out = Path(path)
        out.parent.mkdir(parents=True, exist_ok=True)
        with open(out, "w", encoding="utf-8") as f:
            json.dump(self.get_manifest(), f, indent=2, sort_keys=True)

    # ------------------------------------------------------------------
    # Internal extraction helpers
    # ------------------------------------------------------------------

    def _get_material_record(self, jid: Optional[str]) -> Optional[Any]:
        if jid is None:
            return None
        if jid in self.material_lookup:
            return self.material_lookup[jid]
        proxy = self.material_lookup.get("__STORE_PROXY__")
        if proxy is not None and hasattr(proxy, "resolve"):
            try:
                return proxy.resolve(jid, strict=False)
            except TypeError:
                try:
                    return proxy.resolve(jid)
                except Exception:
                    return None
            except Exception:
                return None
        return None

    def _flatten_material_record(self, record: Optional[Any]) -> Dict[str, Any]:
        if record is None:
            return {}

        flattened: Dict[str, Any] = {}

        if isinstance(record, Mapping):
            flattened.update(record)
        elif pd is not None and hasattr(record, "to_dict"):
            try:
                flattened.update(record.to_dict())
            except Exception:
                pass
        else:
            for attr in (
                "jid",
                "formula",
                "formation_energy",
                "formation_energy_peratom",
                "energy_above_hull",
                "ehull",
                "known_synthesized",
            ):
                if hasattr(record, attr):
                    flattened[attr] = getattr(record, attr)

        # MaterialRecord-like objects keep computed features and raw source fields.
        for attr in ("features", "raw"):
            obj = getattr(record, attr, None)
            if isinstance(obj, Mapping):
                flattened.update(obj)

        # Dict-style nested features/raw.
        for key in ("features", "raw"):
            obj = flattened.get(key)
            if isinstance(obj, Mapping):
                flattened.update(obj)

        return flattened

    def _resolve_pair_jid_columns(
        self,
        df: Any,
        jid_a_col: Optional[str],
        jid_b_col: Optional[str],
    ) -> Tuple[Optional[str], Optional[str]]:
        columns = set(df.columns)
        if jid_a_col and jid_b_col:
            if jid_a_col not in columns or jid_b_col not in columns:
                raise ValueError(f"Requested JID columns not found: {jid_a_col}, {jid_b_col}")
            return jid_a_col, jid_b_col

        candidate_pairs = [
            ("jid_a", "jid_b"),
            ("query_jid", "candidate_jid"),
            ("source_jid", "target_jid"),
            ("material_a_jid", "material_b_jid"),
        ]
        for left, right in candidate_pairs:
            if left in columns and right in columns:
                return left, right

        if "candidate_jid" in columns:
            return None, "candidate_jid"

        raise ValueError(
            "Could not infer pair JID columns. Provide jid_a_col/jid_b_col or include "
            "jid_a/jid_b or query_jid/candidate_jid columns."
        )

    def _pair_summary(self, ann: PairPhysicalAnnotation) -> str:
        return (
            f"pair_label={ann.label}; score={ann.score:.3f}; "
            f"data_completeness={ann.data_completeness:.3f}; "
            f"a={ann.material_a.label}; b={ann.material_b.label}"
        )


# =============================================================================
# Convenience functions for simple imports
# =============================================================================


def annotate_pair_dataframe(
    pair_df: Any,
    material_lookup: Optional[Mapping[str, Any]] = None,
    config: Optional[PhysicalPlausibilityConfig] = None,
    known_synthesized_map: Optional[Mapping[str, Any]] = None,
    jid_a_col: Optional[str] = None,
    jid_b_col: Optional[str] = None,
) -> Any:
    """Convenience wrapper around PhysicalPlausibilityAnnotator."""

    annotator = PhysicalPlausibilityAnnotator(
        material_lookup=material_lookup,
        config=config,
        known_synthesized_map=known_synthesized_map,
    )
    return annotator.annotate_pair_dataframe(pair_df, jid_a_col=jid_a_col, jid_b_col=jid_b_col)


def classify_material_physical_plausibility(
    material: Mapping[str, Any],
    config: Optional[PhysicalPlausibilityConfig] = None,
) -> MaterialPhysicalAnnotation:
    """Classify one material dictionary without constructing a full lookup."""

    annotator = PhysicalPlausibilityAnnotator(config=config)
    jid = material.get("jid") if isinstance(material, Mapping) else None
    return annotator.annotate_material(jid=str(jid) if jid is not None else None, material=material)


def classify_pair_physical_plausibility(
    material_a: Mapping[str, Any],
    material_b: Mapping[str, Any],
    config: Optional[PhysicalPlausibilityConfig] = None,
) -> PairPhysicalAnnotation:
    """Classify one pair of material dictionaries."""

    annotator = PhysicalPlausibilityAnnotator(config=config)
    jid_a = material_a.get("jid") if isinstance(material_a, Mapping) else None
    jid_b = material_b.get("jid") if isinstance(material_b, Mapping) else None
    return annotator.annotate_pair(
        jid_a=str(jid_a) if jid_a is not None else None,
        jid_b=str(jid_b) if jid_b is not None else None,
        material_a=material_a,
        material_b=material_b,
    )


__all__ = [
    "PHYSICAL_PLAUSIBILITY_SCHEMA_VERSION",
    "PHYSICAL_PLAUSIBILITY_OUTPUT_COLUMNS",
    "configure_physical_plausibility_logging",
    "validate_physical_plausibility_config",
    "validate_physical_output_schema",
    "physical_plausibility_manifest",
    "MaterialPhysicalLabel",
    "PairPhysicalLabel",
    "PhysicalPlausibilityConfig",
    "MaterialPhysicalAnnotation",
    "PairPhysicalAnnotation",
    "PhysicalPlausibilityAnnotator",
    "annotate_pair_dataframe",
    "classify_material_physical_plausibility",
    "classify_pair_physical_plausibility",
    "safe_float",
    "safe_bool",
]